import { TaskModel } from "./task-model";

export const tasks: TaskModel[] = [
  {
    id: 1,
    count: 1,
    itemName: "Merrimack Pharmaceuticals, Inc.",
    completed: true,
  },
  {
    id: 2,
    count: 2,
    itemName: "Global Sources Ltd.",
    completed: true,
  },
  {
    id: 3,
    count: 3,
    itemName: "Forestar Group Inc",
    completed: true,
  },
  {
    id: 4,
    count: 4,
    itemName: "TeleTech Holdings, Inc.",
    completed: false,
  },
  {
    id: 5,
    count: 5,
    itemName: "Ingersoll-Rand plc (Ireland)",
    completed: true,
  },
  {
    id: 6,
    count: 6,
    itemName: "Nuveen Maryland Quality Municipal Income Fund",
    completed: false,
  },
  {
    id: 7,
    count: 7,
    itemName: "Sensient Technologies Corporation",
    completed: false,
  },
  {
    id: 8,
    count: 8,
    itemName: "Albany Molecular Research, Inc.",
    completed: true,
  },
  {
    id: 9,
    count: 9,
    itemName: "Nuveen NASDAQ 100 Dynamic Overwrite Fund",
    completed: true,
  },
  {
    id: 10,
    count: 10,
    itemName: "NiSource, Inc",
    completed: false,
  },
  {
    id: 11,
    count: 11,
    itemName: "Nuveen Arizona Quality Municipal Income Fund",
    completed: true,
  },
  {
    id: 12,
    count: 12,
    itemName: "VelocityShares VIX Medium-Term ETN",
    completed: true,
  },
  {
    id: 13,
    count: 13,
    itemName: "Peregrine Pharmaceuticals Inc.",
    completed: true,
  },
  {
    id: 14,
    count: 14,
    itemName: "Cadence Design Systems, Inc.",
    completed: true,
  },
  {
    id: 15,
    count: 15,
    itemName: "Dynex Capital, Inc.",
    completed: false,
  },
  {
    id: 16,
    count: 16,
    itemName: "D.R. Horton, Inc.",
    completed: false,
  },
  {
    id: 17,
    count: 17,
    itemName: "IXYS Corporation",
    completed: false,
  },
  {
    id: 18,
    count: 18,
    itemName: "PowerShares DWA Developed Markets Momentum Portfolio",
    completed: true,
  },
  {
    id: 19,
    count: 19,
    itemName: "ClearBridge Dividend Strategy ESG ETF",
    completed: false,
  },
  {
    id: 20,
    count: 20,
    itemName: "Rubicon Technology, Inc.",
    completed: true,
  },
  {
    id: 21,
    count: 21,
    itemName: "Capitol Federal Financial, Inc.",
    completed: false,
  },
  {
    id: 22,
    count: 22,
    itemName: "Orbotech Ltd.",
    completed: false,
  },
  {
    id: 23,
    count: 23,
    itemName: "Bioverativ Inc.",
    completed: true,
  },
  {
    id: 24,
    count: 24,
    itemName: "BHP Billiton plc",
    completed: true,
  },
  {
    id: 25,
    count: 25,
    itemName: "Avangrid, Inc.",
    completed: false,
  },
  {
    id: 26,
    count: 26,
    itemName: "Beasley Broadcast Group, Inc.",
    completed: false,
  },
  {
    id: 27,
    count: 27,
    itemName: "Cohen & Steers Global Income Builder, Inc.",
    completed: false,
  },
  {
    id: 28,
    count: 28,
    itemName: "Madrigal Pharmaceuticals, Inc.",
    completed: true,
  },
  {
    id: 29,
    count: 29,
    itemName: "WisdomTree Emerging Markets Corporate Bond Fund",
    completed: false,
  },
  {
    id: 30,
    count: 30,
    itemName: "J. W. Mays, Inc.",
    completed: false,
  },
  {
    id: 31,
    count: 31,
    itemName: "Penn National Gaming, Inc.",
    completed: false,
  },
  {
    id: 32,
    count: 32,
    itemName: "Pearson, Plc",
    completed: true,
  },
  {
    id: 33,
    count: 33,
    itemName: "J.B. Hunt Transport Services, Inc.",
    completed: false,
  },
  {
    id: 34,
    count: 34,
    itemName: "Stone Harbor Emerging Markets Total Income Fund",
    completed: false,
  },
  {
    id: 35,
    count: 35,
    itemName: "Wells Fargo & Company",
    completed: true,
  },
  {
    id: 36,
    count: 36,
    itemName: "CapStar Financial Holdings, Inc.",
    completed: false,
  },
  {
    id: 37,
    count: 37,
    itemName: "Fang Holdings Limited",
    completed: false,
  },
  {
    id: 38,
    count: 38,
    itemName: "Vanguard Russell 2000 ETF",
    completed: true,
  },
  {
    id: 39,
    count: 39,
    itemName: "PowerShares KBW Property & Casualty Insurance Portfolio",
    completed: false,
  },
  {
    id: 40,
    count: 40,
    itemName: "Walter Investment Management Corp.",
    completed: false,
  },
  {
    id: 41,
    count: 41,
    itemName: "Eaton Vance Risk-Managed Diversified Equity Income Fund",
    completed: true,
  },
  {
    id: 42,
    count: 42,
    itemName: "CRH PLC",
    completed: false,
  },
  {
    id: 43,
    count: 43,
    itemName: "CIRCOR International, Inc.",
    completed: true,
  },
  {
    id: 44,
    count: 44,
    itemName: "Advantage Oil & Gas Ltd",
    completed: true,
  },
  {
    id: 45,
    count: 45,
    itemName: "ChemoCentryx, Inc.",
    completed: true,
  },
  {
    id: 46,
    count: 46,
    itemName: "iPath US Treasury Flattener ETN",
    completed: true,
  },
  {
    id: 47,
    count: 47,
    itemName: "Signature Bank",
    completed: true,
  },
  {
    id: 48,
    count: 48,
    itemName: "NICE Ltd",
    completed: true,
  },
  {
    id: 49,
    count: 49,
    itemName: "Crown Castle International Corporation",
    completed: true,
  },
  {
    id: 50,
    count: 50,
    itemName: "Helix Energy Solutions Group, Inc.",
    completed: false,
  },
  {
    id: 51,
    count: 51,
    itemName: "Marine Petroleum Trust",
    completed: false,
  },
  {
    id: 52,
    count: 52,
    itemName: "Waste Management, Inc.",
    completed: true,
  },
  {
    id: 53,
    count: 53,
    itemName: "IHS Markit Ltd.",
    completed: true,
  },
  {
    id: 54,
    count: 54,
    itemName: "The Intergroup Corporation",
    completed: false,
  },
  {
    id: 55,
    count: 55,
    itemName: "Innospec Inc.",
    completed: false,
  },
  {
    id: 56,
    count: 56,
    itemName: "Easterly Government Properties, Inc.",
    completed: true,
  },
  {
    id: 57,
    count: 57,
    itemName: "Federated Premier Intermediate Municipal Income Fund",
    completed: false,
  },
  {
    id: 58,
    count: 58,
    itemName: "Bridgepoint Education, Inc.",
    completed: false,
  },
  {
    id: 59,
    count: 59,
    itemName: "Franklin Universal Trust",
    completed: true,
  },
  {
    id: 60,
    count: 60,
    itemName: "Insperity, Inc.",
    completed: false,
  },
  {
    id: 61,
    count: 61,
    itemName: "Amkor Technology, Inc.",
    completed: false,
  },
  {
    id: 62,
    count: 62,
    itemName: "Smart Sand, Inc.",
    completed: true,
  },
  {
    id: 63,
    count: 63,
    itemName: "Olin Corporation",
    completed: false,
  },
  {
    id: 64,
    count: 64,
    itemName: "Public Storage",
    completed: false,
  },
  {
    id: 65,
    count: 65,
    itemName: "Blackrock Municipal Bond Trust",
    completed: false,
  },
  {
    id: 66,
    count: 66,
    itemName: "Chemung Financial Corp",
    completed: false,
  },
  {
    id: 67,
    count: 67,
    itemName: "Cencosud S.A.",
    completed: true,
  },
  {
    id: 68,
    count: 68,
    itemName: "Hardinge Inc.",
    completed: false,
  },
  {
    id: 69,
    count: 69,
    itemName: "Capital One Financial Corporation",
    completed: false,
  },
  {
    id: 70,
    count: 70,
    itemName: "Knowles Corporation",
    completed: false,
  },
  {
    id: 71,
    count: 71,
    itemName: "Dimension Therapeutics, Inc.",
    completed: true,
  },
  {
    id: 72,
    count: 72,
    itemName: "CommScope Holding Company, Inc.",
    completed: true,
  },
  {
    id: 73,
    count: 73,
    itemName: "Alpine Total Dynamic Dividend Fund",
    completed: true,
  },
  {
    id: 74,
    count: 74,
    itemName: "Alabama Power Company",
    completed: true,
  },
  {
    id: 75,
    count: 75,
    itemName: "Amazon.com, Inc.",
    completed: true,
  },
  {
    id: 76,
    count: 76,
    itemName: "Acorn International, Inc.",
    completed: true,
  },
  {
    id: 77,
    count: 77,
    itemName: "Integer Holdings Corporation",
    completed: false,
  },
  {
    id: 78,
    count: 78,
    itemName: "Pluristem Therapeutics, Inc.",
    completed: true,
  },
  {
    id: 79,
    count: 79,
    itemName: "Texas Roadhouse, Inc.",
    completed: true,
  },
  {
    id: 80,
    count: 80,
    itemName: "Stellar Acquisition III Inc.",
    completed: false,
  },
  {
    id: 81,
    count: 81,
    itemName: "The Charles Schwab Corporation",
    completed: true,
  },
  {
    id: 82,
    count: 82,
    itemName: "BlackRock Resources",
    completed: true,
  },
  {
    id: 83,
    count: 83,
    itemName: "Texas Instruments Incorporated",
    completed: false,
  },
  {
    id: 84,
    count: 84,
    itemName: "Berkshire Hathaway Inc.",
    completed: false,
  },
  {
    id: 85,
    count: 85,
    itemName: "Axis Capital Holdings Limited",
    completed: true,
  },
  {
    id: 86,
    count: 86,
    itemName: "Home Bancorp, Inc.",
    completed: true,
  },
  {
    id: 87,
    count: 87,
    itemName: "Proofpoint, Inc.",
    completed: false,
  },
  {
    id: 88,
    count: 88,
    itemName: "BofI Holding, Inc.",
    completed: false,
  },
  {
    id: 89,
    count: 89,
    itemName: "Ohio Valley Banc Corp.",
    completed: true,
  },
  {
    id: 90,
    count: 90,
    itemName: "BioShares Biotechnology Clinical Trials Fund",
    completed: false,
  },
  {
    id: 91,
    count: 91,
    itemName: "Red Lion Hotels Corporation",
    completed: true,
  },
  {
    id: 92,
    count: 92,
    itemName: "Education Realty Trust Inc.",
    completed: false,
  },
  {
    id: 93,
    count: 93,
    itemName: "Summit Hotel Properties, Inc.",
    completed: true,
  },
  {
    id: 94,
    count: 94,
    itemName: "Aluminum Corporation of China Limited",
    completed: true,
  },
  {
    id: 95,
    count: 95,
    itemName: "Burcon NutraScience Corp",
    completed: false,
  },
  {
    id: 96,
    count: 96,
    itemName: "Inpixon ",
    completed: true,
  },
  {
    id: 97,
    count: 97,
    itemName: "Stellus Capital Investment Corporation",
    completed: false,
  },
  {
    id: 98,
    count: 98,
    itemName: "First Trust Canada AlphaDEX Fund",
    completed: false,
  },
  {
    id: 99,
    count: 99,
    itemName: "Piedmont Office Realty Trust, Inc.",
    completed: false,
  },
  {
    id: 100,
    count: 100,
    itemName: "Eleven Biotherapeutics, Inc.",
    completed: false,
  },
];
